### ISSUE TITLE
filter returns false

### ISSUE THREAD

**Issue by RANSIDRAT** [strangerstudios/pmpro-email-confirmation#22]
filter returns false until validated doesn't stop access to entry level (FREE) membership

**Comment by andrewlimaza** [comment]
Hi @RANSIDRAT 

Do you have more information on how to replicate this? We're busy working on updating the Email Confirmation Add On. This may have been resolved between the time of this issue and today.

Please let me know, as I believe this has been fixed and user's shouldn't gain access to anything (pages/posts/membership shortcode) until they are validated.
