### ISSUE TITLE
Feature Request: Custom redirect after email confirmation

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-email-confirmation#26]
Instead of simply redirecting to the website's homepage, it would make sense to allow redirection to a page that says something like "Your email address has successfully confirmed."

This would avoid confusion about whether the confirmation link worked or not.

**Comment by dparker1005** [comment]
There is currently a workaround that can be used to achieve this, though this seems like functionality that would be nice to have as a dropdown: https://www.paidmembershipspro.com/redirect-to-the-membership-account-page-after-email-confirmation/

**Comment by andrewlimaza** [comment]
New filters added in for the time being (UI may come later):

Logged-in users validate redirect - pmproec_logged_in_validate_redirect
Logged-out users validate redirect - pmproec_logged_out_validate_redirect
