### ISSUE TITLE
Feature request: add additional confirmation text to editable Email Templates

### ISSUE THREAD

**Issue by LMNTL** [strangerstudios/pmpro-email-confirmation#27]
The "IMPORTANT! You must follow this link[...]" text is added to the checkout email using the "pmpro_email_body" filter, and isn't editable from admin when using the Email Templates Add On. 

Forum ticket (mods only): https://www.paidmembershipspro.com/forums/topic/email-confirmation-add-on-change-email-template/

**Comment by andrewlimaza** [comment]
For now, you may need to unhook the filter and then add a custom variable using the pmpro_email_data filter for something like '!!validation_link!!'

**Comment by andrewlimaza** [comment]
I understand the request now, there is already a !!validation_link!! that may be used. It is now added to text wrapping for i18n and should be translatable via a PO/MO file.

Will mark this as resolved.
