### ISSUE TITLE
Fix the Email Confirmation Process for users added manually

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-email-confirmation#30]
When a user is added via the "Add Member Add On", they don't get a confirmation link via email, they only get the email when they try to log in and click the "Resend Confirmation" link.
There isn't ab option to manually confirm users when they are added via the "Add Member Add on"

Related ticket: https://www.paidmembershipspro.com/forums/topic/problem-with-paid-member-pro-avtivations/

**Comment by andrewlimaza** [comment]
User's are automatically validated when manually added like this. There's a fix to give all user's that are manually added a 'validated' status.

**Comment by andrewlimaza** [comment]
This was a bug with user's that were manually added in some cases, it's fixed as of V0.6
