### ISSUE TITLE
There needs to be a space between the “address.” and “Important” as they are separate sentences.

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-email-confirmation#31]
There needs to be a space between the “address.” and “Important” as they are separate sentences.

![image](https://user-images.githubusercontent.com/22073464/81548822-2c807580-937e-11ea-99e2-efcfd78cfc79.png)

**Comment by femiyb** [comment]
This only happens on Restricted Pages

**Comment by andrewlimaza** [comment]
Thanks for the fix! :)
