### ISSUE TITLE
"Confirm your email address" shown when not the cause of restricting access

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-email-confirmation#37]
When restricting access, the code currently allows access if:
1. The level the user has does not require email confirmation
2. If the user has confirmed their email
3. If the "confirm" usermeta was not added to the user (ie. the user did not get level through checkout process)

The check we do to show the PMProEC email confirmation message, however, is shown even if the usermeta is not present for a given user: https://github.com/strangerstudios/pmpro-email-confirmation/blob/88b37d50716ea03091a7dd42b7d753d1e167591e/pmpro-email-confirmation.php#L556

What this means is if a user does not go through checkout for an email confirmation level and tries to view a post restricted to a different level (say they were given silver which would require confirmation if they had checked out, and then then try to view a page only for gold members), the error shown will say that they need to confirm their email but in reality they just have the wrong level.

Side note... the restriction behavior I mentioned at the top of this post may be changing with the MMPU compatibility commit here: https://github.com/strangerstudios/pmpro-email-confirmation/commit/88b37d50716ea03091a7dd42b7d753d1e167591e

**Comment by andrewlimaza** [comment]
I've fixed this I believe. If there is no validation key found we can assume that the user doesn't need to be validated (given a level by an admin etc). PMPro in this instance (to your reference) will still restrict content showing that they need membership access if they don't have access to a particular post.
