### ISSUE TITLE
Confirmation email not sent with “Accept Payments in Stripe”  

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/pmpro-email-confirmation#52]
**Describe the bug**
When you make a purchase a confirmation email is not sent.

**To Reproduce**
1. Go to **Settings > Payment Gateway & SSL Settings**, then scroll down to the **Other Stripe Settings** section, and select **Accept payments in Stripe** within the **Payment Flow** option
2. Make a purchase
3. A confirmation email is not sent

**Expected behavior**
You should receive a confirmation email.

This came up in ticket (ID 510557) and I could replicate. However, when “Accept payments on this site” is unselected a confirmation email is sent. 

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/). 

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.11.2, AWeber Add On 1.3.3, WordPress 6.2.2, PHP 7.4.30 
```
</details>

**Comment by dparker1005** [comment]
Closing as we are no longer able to replicate this issue.
